name: Pre-Qual Onboarding Issue
description: Pre-Qual Onboarding Issue
title: "[Onboarding]: "
labels: ["Pre-Qual", "Onboarding"]
# assignees:
#   - octocat
body:
  - type: checkboxes
    id: attached-governance-agreement
    attributes:
      label: Have you attached a copy of the signed governance agreement to the issue?
      description: Have you attached a copy of the signed governance agreement to the issue? 
      options:
        - label: I have attached a copy of the signed governance agreement to the issue. 
          required: true
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false
  - type: textarea
    id: what-happened
    attributes:
      label: What happened?
      description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "A bug happened!"
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: Version
      description: What version of our software are you running?
      options:
        - 1.0.2 (Default)
        - 1.0.3 (Edge)
      default: 0
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What browsers are you seeing the problem on?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
        - Microsoft Edge
  - type: textarea
    id: logs
    attributes:
      label: Relevant log output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      render: shell
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://example.com). 
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true


# ---
# name: Pre-Qual Onboarding Issue
# about: 
# labels: onboarding,
# ---

# ## Signed governance agreement

# *Attach to this issue a copy of the signed governance agreement.*

# ## pre-qual environment service account

# *provide the service account for the pre-qual environment.*

# ## Automated Testing URLs (Optional)

# *provide the automated testing required URLs*
# *e.g. flight planners, test version providers, and prod version providers*

# ## DSS URLs and host names (Optional)

# *If you intend to bring your own DSS then provide the required information*
# *e.g. your DSS's URL and the hostname for your cockroachDB nodes*
