name: Automated Test Configuration Change
description: Request a change to the automated test configuration. 
labels: ["automated_test_config_change"]
body:
  - type: checkboxes
    attributes:
      label: Which automate test do you wish to make the change to
      options:
        - label: "Pre-qual: <USP>_pre_qual"
        - label: "Qual-partners: participant_readiness_assessment"
        - label: "Qual-partners: simulation_fitness"
        - label: "Qual-partners: production_fitness"
        - label: "Other" 
  - type: textarea
    attributes:
      label: Describe the change you wish made to the automate test configuration.
      value: "Describe your operational practicality simulation, include artifacts as desired (e.g. KMLs)"
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        For changes to the `exploratory` automated test please contact the technical committee.  