name: Pre-Qual Onboarding Issue
description: Pre-Qual Onboarding Issue
title: "[Onboarding]: "
labels: ["Pre-Qual", "Onboarding"]
body:
  - type: textarea
    id: attached-governance-agreement 
    attributes:
      label: Attach copy of signed governance agreement here. 
      value: "*Attach your signed governance agreement here*"
  - type: checkboxes
    id: attached-governance-agreement
    attributes:
      label: Have you attached a copy of the signed governance agreement to the issue?
      description: Have you attached a copy of the signed governance agreement to the issue? 
      options:
        - label: I have attached a copy of the signed governance agreement to the issue. 
          required: true
  
