name: Pre-Qual Onboarding Issue
description: Pre-Qual Onboarding Issue
title: "[Onboarding]: "
labels: ["Pre-Qual", "Onboarding"]
body:
  - type: textarea
    id: Attached-governance-agreement-textarea
    attributes:
      label: Attached a copy of the signed governance agreement.
      # description: Also tell us, what did you expect to happen?
      placeholder: Tell us what you see!
      value: "Attached a copy of the signed governance agreement"
    validations:
      required: true
  - type: checkboxes
    id: attached-governance-agreement-checkbox
    attributes:
      label: Have you attached a copy of the signed governance agreement to the issue?
      description: Have you attached a copy of the signed governance agreement to the issue? 
      options:
        - label: I have attached a copy of the signed governance agreement to the issue. 
          required: true
  
