name: Operational Practicality Issue
description: Document the results from an operational practicality simulation
title: "Operational practicality simulation for <insert company name here>"
labels: ["operational-practicality"]
body:
  - type: textarea
    id: attached-test-results-textarea
    attributes:
      label: Describe your operational practicality simulation, include artifacts as desired (e.g. KMLs)
      value: "Describe your operational practicality simulation, include artifacts as desired (e.g. KMLs)"
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Once this issue is submitted please ensure that you get approvals from the required parties as documented in the governance agreement.    
  
  
