name: Operational Practicality Issue
description: Document the results from an operational practicality simulation
title: "Operational practicality simulation for <insert company name here>"
labels: ["operational-practicality"]
body:
  - type: textarea
    id: attached-test-results-textarea
    attributes:
      label: Describe your operational practicality simulation, include artifacts as desired (e.g. KMLs)
      value: "Describe your operational practicality simulation, include artifacts as desired (e.g. KMLs)"
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Assign this issue to the operational committee representative from other companies you performed operational practicality simulation with. |
        The expectation is that they will comment on the issue to indicate their approval.  
  
