name: Pre-Qual Onboarding Issue
description: Request onboarding of your USP to the pre-qual environment
title: "pre-qual onboarding request for <insert company name here>"
labels: ["pre-qual", "onboarding"]
body:
  - type: input
    id: contact
    attributes:
      label: Provide your contact email
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: true
  - type: textarea
    id: attached-joinder-agreement-textarea
    attributes:
      label: Attached a copy of the signed joinder agreement.
      value: "Attached a copy of the signed joinder agreement"
    validations:
      required: true
  - type: checkboxes
    id: attached-joinder-agreement-checkbox
    attributes:
      label: Have you attached a copy of the signed joinder agreement to the issue?
      options:
        - label: I have attached a copy of the signed joinder agreement to the issue. 
          required: true
  - type: input
    id: service-account
    attributes:
      label: Pre-qual environment service account
      description: what is the service account you wish to have onboarded to the pre-qual environment? 
      placeholder: ex. *.iam.gserviceaccount.com
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## The following URLs are required if you intend to use the provided pre-qual automated test runner (recommended).
  - type: input
    id: flight-planner-url
    attributes:
      label: Provide the base URL for your pre-qual flight planner
    validations:
      required: false
  - type: input
    id: test-version-url
    attributes:
      label: Provide the base URL for your pre-qual test version provider
    validations:
      required: false
  - type: input
    id: prod-version-url
    attributes:
      label: Provide the base URL for your pre-qual prod version provider
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        ## The following URL and Hostnames are required if intend to bring your own DSS.
  - type: input
    id: DSS-url
    attributes:
      label: Provide the base URL for your pre-qual DSS
    validations:
      required: false
  - type: textarea
    id: dss-crdb-nodes-textarea
    attributes:
      label: Provide the hostnames of each of your cockroach DB nodes
      value: "example: \n
        0.db.dss.prequal.usp.com \n
        1.db.dss.prequal.usp.com \n
        2.db.dss.prequal.usp.com"
    validations:
      required: false      
  
  
