name: Qual-Partners Onboarding Issue
description: Request onboarding of your USP to the qual-partners environment
title: "Qual-partners environment onboarding request for <insert company name here>"
labels: ["qual-partners", "onboarding"]
body:
  - type: textarea
    id: attached-test-results-textarea
    attributes:
      label: Attached a copy of the automated testing results (.zip)
      value: "Attached a copy of the automated testing results (.zip)"
    validations:
      required: true
  - type: checkboxes
    id: attached-test-results-checkbox
    attributes:
      label: Have you a copy of the automated testing results (.zip) to the issue?
      options:
        - label: I have a copy of the automated testing results (.zip) to the issue. 
          required: true
  - type: checkboxes
    id: test-results-pass-checkbox
    attributes:
      label: Do the test results show your USP has achieved a passing result?
      options:
        - label: I have reviewed the results and my USP has a passing result. 
          required: true
  - type: input
    id: service-account
    attributes:
      label: Qual-partners environment service account
      description: what is the service account you wish to have onboarded to the qual-partners environment? 
      placeholder: ex. *.iam.gserviceaccount.com
    validations:
      required: true
  - type: input
    id: flight-planner-url
    attributes:
      label: Provide the base URL for your qual-partners flight planner
    validations:
      required: true
  - type: input
    id: test-version-url
    attributes:
      label: Provide the base URL for your qual-partners test version provider
    validations:
      required: true
  - type: input
    id: prod-version-url
    attributes:
      label: Provide the base URL for your qual-partners prod version provider
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## The following URL and Hostnames are required if intend to bring your own DSS.
  - type: input
    id: DSS-url
    attributes:
      label: Provide the base URL for your qual-partners DSS
    validations:
      required: false
  - type: textarea
    id: dss-crdb-nodes-textarea
    attributes:
      label: Provide the hostnames of each of your cockroach DB nodes
      value: "example: \n
        0.db.dss.prequal.usp.com \n
        1.db.dss.prequal.usp.com \n
        2.db.dss.prequal.usp.com"
    validations:
      required: false      
  
  
